apiVersion: apps/v1
kind: Deployment
metadata:
  name: m3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m3
  template:
    metadata:
      labels:
        app: m3
    spec:
      containers:
        - name: m3-container
          image: module3:1
          ports:
            - containerPort: 8085
